### PR TITLE
Update README.md to be more aligned with iOS

### PR DESCRIPTION
**Pull request by ustroetz**

### CODE REVIEW

**Comment by shadyabidi** [comment]
LGTM

**Comment by Zlate87** [comment]
The main issue I see with adding numbers manually is that it is very easy to mess them up in the future when we add or remove something. However, if this is acceptable, go for it :)

Additionally, if we do this to be alligned with how it is done in the iOS documentation, we should add numbers also to the sub sections (Like 4.1 SearchTripEvent).

**Comment by ustroetz** [comment]
Agree with you that it is harder to maintain with numbers. But since this document shall stay quiet short I don't think we run into numbering issues. 

Right now the sub-sections are a little inconsistent. This makes it hard to add numbers in sub-headings (e.g. JavaDocs). 

I leave it up to you to decide to merge it or not. In the end you are the main contributor and have to be proud on it. It probably will never be possible to align iOS and Android fully.

**Comment by elmoswelt** [comment]
I like the approach here using PR's for this stuff! :) Let's continue working on that one. I think that documentation etc. can be owned by your team as well. Everything which is structure related etc. can be decided from your team, what do you think guys?

**Comment by Zlate87** [comment]
Since you leave the decision up to me, I will not merge the pull request. 

The main reason is that we are not yet even to version 1.0.0 and for sure we will need to do some modifications in the documentation. 
Additionally I do not see what is the value that the numbers bring, since anyway the table of content is clickable and there is no need to scroll to the topic, but you can jump directly to it. 

If at any point this needs to be changed, feel free to reopen it.

**Pull request closed without merging**
